name: 'Authenticate to Alibaba Cloud'
description: |-
  Authenticate to Alibaba Cloud with GitHub Actions OIDC tokens.
inputs:
  audience:
    description: |-
      The value for the audience (aud) parameter in GitHub's generated OIDC
      token.
    default: 'actions.github.com'
    required: false
  region:
    description: |-
      Alibaba Cloud Region
    default: 'ap-southeast-1'
    required: false
  role-arn-to-assume:
    description: |-
      Use the OIDC token to assume an RAM role.
    required: true
  oidc-provider-arn:
    description: |-
      The arn of OIDC provider.
    required: true
  role-duration-seconds:
    description: |-
      Role duration in seconds.
    default: '3600'
    required: false
  role-session-name:
    description: |-
      Role session name
    default: 'github-actions-<orgName>-<repoName>'
    required: false
  export-environment-variables:
    description: |-
      If true, the action will export common environment variables which are
      known to be consumed by popular downstream libraries and tools, including:
      - ALIBABA_CLOUD_ACCESS_KEY_ID
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET
      - ALIBABA_CLOUD_SECURITY_TOKEN
      - ALICLOUD_ACCESS_KEY
      - ALICLOUD_SECRET_KEY
      - ALICLOUD_ACCESS_KEY_STS_TOKEN
      - ALIBABACLOUD_ACCESS_KEY_ID
      - ALIBABACLOUD_ACCESS_KEY_SECRET
      - ALIBABACLOUD_SECURITY_TOKEN
      If false, the action will not export any environment variables.
    default: 'false'
    required: false

  set-outputs:
    description: |-
      If true, the action will setting credentials as action outputs, including:
      - access-key-id
      - access-key-secret
      - security-token
    default: 'false'
    required: false

  retries:
    description: |-
      Number of times to retry a failed authentication attempt.
    default: '3'
    required: false

outputs:
  access-key-id:
    description: access key id

  access-key-secret:
    description: access key secret

  security-token:
    description: security token

branding:
  icon: 'lock'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
