name: test

on:
  workflow_dispatch:

jobs:
  credentials:
    runs-on: ubuntu-latest
    name: credentials
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test oidc
        uses: ./ # Uses an action in the root directory
        with:
          role-arn-to-assume: '${{ secrets.ROLE_ARN }}'
          oidc-provider-arn: '${{ secrets.OIDC_ARN }}'

      - name: test using credentials
        run: |
          wget https://github.com/aliyun/aliyun-cli/releases/download/v3.0.133/aliyun-cli-linux-3.0.133-amd64.tgz
          tar zxvf aliyun-cli-linux-3.0.133-amd64.tgz
          ./aliyun-cli sts GetCallerIdentity | jq .IdentityType
